# Generated by Django 3.2.9 on 2022-05-25 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineapp', '0004_rename_max_quantity_available_product_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('basket_no', models.CharField(max_length=36)),
                ('pay_code', models.CharField(max_length=36)),
                ('paid_order', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
