# Generated by Django 3.2.9 on 2022-05-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0005_auto_20220525_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='basket_no',
        ),
    ]
