# Generated by Django 3.2.9 on 2022-05-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0007_shopcart_basket_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='basket_no',
        ),
    ]
