# Generated by Django 3.2.9 on 2022-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0008_remove_shopcart_basket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='basket_no',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
